"""Minimal Streamlit UI for local inventory analysis."""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

import streamlit as st

from main import run_analysis
from tools.load_data import load_threshold_config


def _health_status() -> Dict[str, str]:
    """Return simple health indicators for sidebar."""
    neo4j_status = "disabled" if os.environ.get("NEO4J_ENABLED", "true").lower() == "false" else "enabled"
    return {
        "neo4j": neo4j_status,
        "ollama_model": "llama3.2:1b",
        "last_check": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


def _render_summary(payload: Dict[str, Any]) -> None:
    """Render summary cards and sku-level recommendations."""
    summary = payload.get("summary", {})
    recs = payload.get("recommendations", [])

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Critical", int(summary.get("critical_count", 0)))
    col2.metric("Watch", int(summary.get("watch_count", 0)))
    col3.metric("Healthy", int(summary.get("healthy_count", 0)))
    col4.metric("Overstock", int(summary.get("overstock_count", 0)))

    st.subheader("SKU Recommendations")
    for rec in recs:
        with st.container(border=True):
            st.markdown(f"**{rec.get('sku_id')} - {rec.get('name')}**")
            st.caption(f"Status: {rec.get('status_emoji')} {rec.get('status')} | Trend: {rec.get('velocity_trend')}")
            st.write(
                f"Days of stock: {rec.get('days_of_stock'):.2f} | Reorder qty: {rec.get('reorder_qty'):.2f} | "
                f"Urgency days: {rec.get('reorder_urgency_days'):.2f}"
            )
            st.write(f"Action: {rec.get('recommended_action')}")
            st.write(rec.get("plain_english_explanation"))


def main() -> None:
    """Run Streamlit application."""
    st.set_page_config(page_title="Inventory Optimization Agent", layout="wide")
    st.title("Inventory Optimization AI Agent")
    st.warning(
        "⚠️ ADVISORY ONLY: This analysis is generated by an AI decision-support tool using synthetic mock data. "
        "All recommendations require human review and validation before any action is taken."
    )

    with st.sidebar:
        st.header("System Status")
        status = _health_status()
        st.write(f"Neo4j: {status['neo4j']}")
        st.write(f"Model: {status['ollama_model']}")
        st.write(f"Last Check: {status['last_check']}")

    uploaded = st.file_uploader("Upload inventory CSV or JSON", type=["csv", "json"])
    run = st.button("Run Analysis", type="primary")

    if run:
        if uploaded is None:
            st.error("Please upload a CSV or JSON file first.")
            return

        with tempfile.TemporaryDirectory() as temp_dir:
            data_path = Path(temp_dir) / uploaded.name
            data_path.write_bytes(uploaded.read())

            config = load_threshold_config("config/thresholds.yaml")
            config["data_path"] = str(data_path)
            config["config_path"] = "config/thresholds.yaml"
            config["kg_seed_path"] = "data/kg_seed.json"

            payload = run_analysis(config)
            _render_summary(payload)
            st.download_button(
                "Download JSON Output",
                data=json.dumps(payload, indent=2, ensure_ascii=False),
                file_name=f"inventory_run_{payload.get('run_id', 'unknown')}.json",
                mime="application/json",
            )


if __name__ == "__main__":
    main()
