"""CLI entrypoint for Inventory Optimization AI Agent."""

from __future__ import annotations

import argparse
import json
import logging
import math
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from agent.graph import build_graph
from agent.state import AgentState
from tools.load_data import load_threshold_config

DISCLAIMER = (
    "⚠️ ADVISORY ONLY: This analysis is generated by an AI decision-support tool "
    "using synthetic mock data. All recommendations require human review and "
    "validation before any action is taken. This tool does not place orders, "
    "modify systems, or reflect real commercial inventory. Always consult your "
    "supply chain team before acting on these suggestions."
)


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Inventory Optimization AI Agent")
    parser.add_argument("--data", default="data/inventory_mock.csv", help="Path to CSV/JSON inventory data")
    parser.add_argument("--config", default="config/thresholds.yaml", help="Path to YAML config")
    parser.add_argument("--output", default=None, help="Optional output JSON file path")
    parser.add_argument(
        "--scenario",
        action="append",
        default=[],
        help="Override values (e.g. --scenario lead_time=14 --scenario healthy_dos_min=12)",
    )
    parser.add_argument("--no-report", action="store_true", help="Disable markdown report generation")
    parser.add_argument(
        "--format",
        choices=["table", "json"],
        default="table",
        help="Console output format",
    )
    return parser.parse_args()


def _parse_scenario_overrides(scenarios: List[str]) -> Dict[str, float]:
    """Parse --scenario key=value overrides."""
    parsed: Dict[str, float] = {}
    for item in scenarios:
        if "=" not in item:
            continue
        key, value = item.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        try:
            parsed[key] = float(value)
        except ValueError:
            continue
    return parsed


def _apply_overrides(config: Dict[str, Any], overrides: Dict[str, float]) -> Dict[str, Any]:
    """Apply threshold/default scenario overrides to config copy."""
    updated = json.loads(json.dumps(config))
    thresholds = updated.setdefault("thresholds", {})
    defaults = updated.setdefault("defaults", {})

    for key, value in overrides.items():
        if key in {"healthy_dos_min", "watch_dos_min", "critical_dos_max", "overstock_dos_min"}:
            thresholds[key] = value
        elif key in {"lead_time", "lead_time_days"}:
            defaults["lead_time_days"] = int(value)
        elif key in {"safety_stock", "default_safety_stock"}:
            defaults["safety_stock"] = value

    return updated


def _safe_number(value: float) -> str:
    """Render finite and non-finite numbers safely for display."""
    if isinstance(value, float) and math.isinf(value):
        return "inf"
    return f"{value:.2f}"


def print_table(metrics: List[Dict[str, Any]]) -> None:
    """Print a compact table to stdout."""
    headers = ["sku_id", "status", "dos", "reorder_qty", "urgency_days", "trend"]
    widths = [10, 10, 10, 12, 14, 9]

    def row(values: List[str]) -> str:
        return " ".join(value.ljust(width) for value, width in zip(values, widths))

    print(row(headers))
    print("-" * (sum(widths) + len(widths) - 1))

    for item in metrics:
        print(
            row(
                [
                    str(item["sku_id"]),
                    f"{item['status_emoji']} {item['status']}",
                    _safe_number(float(item["days_of_stock"])),
                    _safe_number(float(item["reorder_qty"])),
                    _safe_number(float(item["reorder_urgency_days"])),
                    item["velocity_trend"],
                ]
            )
        )


def _print_comparison(base_payload: Dict[str, Any], scenario_payload: Dict[str, Any]) -> None:
    """Print side-by-side summary comparison baseline vs scenario."""
    base = base_payload.get("summary", {})
    scenario = scenario_payload.get("summary", {})
    fields = ["critical_count", "watch_count", "healthy_count", "overstock_count"]

    print("Scenario Comparison (baseline -> scenario)")
    for field in fields:
        left = int(base.get(field, 0))
        right = int(scenario.get(field, 0))
        print(f"- {field}: {left} -> {right} (delta {right - left:+d})")


def _generate_report(payload: Dict[str, Any], output_path: Path) -> Path:
    """Generate markdown report card with executive summary and top actions."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = output_path.parent / f"report_{timestamp}.md"

    summary = payload.get("summary", {})
    recommendations = payload.get("recommendations", [])
    top_actions = [rec for rec in recommendations if rec.get("status") in {"critical", "watch"}][:5]

    lines = [
        "# Inventory Optimization Report Card",
        "",
        f"- Run ID: {payload.get('run_id', 'unknown')}",
        f"- Generated At: {payload.get('generated_at', 'unknown')}",
        "",
        "## Executive Summary",
        f"- Total SKUs analyzed: {summary.get('total_skus_analyzed', 0)}",
        f"- Critical: {summary.get('critical_count', 0)}",
        f"- Watch: {summary.get('watch_count', 0)}",
        f"- Healthy: {summary.get('healthy_count', 0)}",
        f"- Overstock: {summary.get('overstock_count', 0)}",
        f"- Overall Health: {summary.get('overall_health', 'unknown')}",
        "",
        "## Top Actions",
    ]

    if top_actions:
        for action in top_actions:
            lines.append(f"- {action.get('sku_id')}: {action.get('recommended_action', 'No action provided')}")
    else:
        lines.append("- No high-priority actions identified in this run.")

    lines.extend(["", "## Advisory Disclaimer", payload.get("disclaimer", DISCLAIMER)])
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def run_analysis(config: Dict[str, Any]) -> Dict[str, Any]:
    """Execute full LangGraph analysis and return output payload."""
    state: AgentState = {
        "run_id": str(uuid.uuid4()),
        "started_at": datetime.now(timezone.utc).isoformat(),
        "config": config,
        "raw_records": [],
        "sku_records": [],
        "sku_metrics": [],
        "sku_contexts": [],
        "rule_results": {},
        "recommendations": [],
        "llm_prompts": {},
        "llm_responses": {},
        "llm_retries": {},
        "current_node": "",
        "errors": [],
        "warnings": [],
        "partial_data": False,
        "graph_source": "default",
        "output_valid": False,
        "final_output": None,
    }

    app = build_graph()
    final_state = app.invoke(state)
    return final_state.get("final_output") or {
        "run_id": state["run_id"],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "total_skus_analyzed": 0,
            "critical_count": 0,
            "watch_count": 0,
            "healthy_count": 0,
            "overstock_count": 0,
            "skus_skipped": 0,
            "overall_health": "poor",
            "top_priority_skus": [],
        },
        "recommendations": [],
        "metadata": {
            "llm_model": config.get("ollama", {}).get("model", "llama3.2:1b"),
            "graph_source": "default",
            "config_version": "1.0.0",
            "execution_time_ms": 0,
            "partial_data": True,
            "errors": final_state.get("errors", []),
            "warnings": final_state.get("warnings", []),
        },
        "disclaimer": DISCLAIMER,
    }


def main() -> None:
    """Execute the agent workflow and render output."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s - %(message)s")
    args = parse_args()

    base_config = load_threshold_config(Path(args.config))
    base_config["data_path"] = str(Path(args.data))
    base_config["config_path"] = str(Path(args.config))
    base_config["kg_seed_path"] = "data/kg_seed.json"

    overrides = _parse_scenario_overrides(args.scenario)
    scenario_config = _apply_overrides(base_config, overrides) if overrides else base_config
    if overrides:
        scenario_config["scenario_overrides"] = overrides
    payload = run_analysis(scenario_config)

    if overrides:
        baseline_payload = run_analysis(base_config)
        _print_comparison(baseline_payload, payload)

    output_path = Path(args.output) if args.output else Path("results") / f"{payload['run_id']}.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, default=str), encoding="utf-8")

    report_path = None if args.no_report else _generate_report(payload, output_path)

    if args.format == "json":
        print(json.dumps(payload, indent=2, ensure_ascii=False, default=str))
    else:
        print_table(payload.get("recommendations", []))
        print()
        print(json.dumps(payload.get("summary", {}), indent=2))
        print()
        print(f"Output written to: {output_path}")
        if report_path is not None:
            print(f"Report written to: {report_path}")
        print(DISCLAIMER)


if __name__ == "__main__":
    main()
