"""LangGraph node to assemble final Phase 1 output payload."""

from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timezone
import json
from typing import Dict, List

from agent.state import AgentState, SKURecommendation

DISCLAIMER = (
    "⚠️ ADVISORY ONLY: This analysis is generated by an AI decision-support tool "
    "using synthetic mock data. All recommendations require human review and "
    "validation before any action is taken. This tool does not place orders, "
    "modify systems, or reflect real commercial inventory. Always consult your "
    "supply chain team before acting on these suggestions."
)


def _recommended_action(status: str) -> str:
    """Return a deterministic action string by status."""
    if status == "critical":
        return "Consider immediate reorder review to reduce stockout risk."
    if status == "watch":
        return "Consider scheduling a reorder in the next planning cycle."
    if status == "overstock":
        return "Consider slowing replenishment and monitoring demand movement."
    return "Maintain current policy and continue routine monitoring."


def _overall_health(summary: Dict[str, int]) -> str:
    """Derive overall health category from status counts."""
    if summary["critical_count"] >= max(1, summary["total_skus_analyzed"] // 4):
        return "poor"
    if summary["critical_count"] > 0 or summary["watch_count"] > summary["healthy_count"]:
        return "fair"
    return "good"


def format_output_node(state: AgentState) -> AgentState:
    """Build PRD schema-aligned output with template placeholders for Phase 1."""
    state["current_node"] = "format_output"

    metrics_by_sku = {metric.sku_id: metric for metric in state["sku_metrics"]}
    records_by_sku = {record.sku_id: record for record in state["sku_records"]}
    contexts_by_sku = {context.sku_id: context for context in state["sku_contexts"]}

    recommendations: List[SKURecommendation] = []
    recommendation_dicts: List[Dict[str, object]] = []

    for sku_id, metric in metrics_by_sku.items():
        record = records_by_sku.get(sku_id)
        if record is None:
            continue

        llm_payload = state["llm_responses"].get(sku_id)
        llm_struct: Dict[str, str] = {}
        if llm_payload:
            try:
                parsed = json.loads(llm_payload)
                if isinstance(parsed, dict):
                    llm_struct = {k: str(v) for k, v in parsed.items()}
            except json.JSONDecodeError:
                llm_struct = {}

        rec = SKURecommendation(
            sku_id=sku_id,
            name=record.name,
            status=metric.status,
            status_emoji=metric.status_emoji,
            days_of_stock=metric.days_of_stock,
            reorder_qty=metric.reorder_qty,
            reorder_urgency_days=metric.reorder_urgency_days,
            recommended_action=llm_struct.get("action", _recommended_action(metric.status)),
            plain_english_explanation=llm_struct.get("explanation", "Template pending."),
            risk_tags=list(contexts_by_sku.get(sku_id).risk_tags if sku_id in contexts_by_sku else []),
            confidence=llm_struct.get("confidence", "medium"),
            data_quality_flag=None,
        )
        recommendations.append(rec)

        context = contexts_by_sku.get(sku_id)
        seasonal_factor = context.seasonal_factor if context else 1.0
        context_source = context.context_source if context else "default"
        category_avg_dos = context.category_avg_dos if context else 30.0

        recommendation_dicts.append(
            {
                **asdict(rec),
                "category": record.category,
                "seasonal_factor": seasonal_factor,
                "category_avg_dos": category_avg_dos,
                "formula_used": (
                    "reorder_qty = (avg_daily_sales x lead_time_days) + "
                    "safety_stock - current_stock"
                ),
                "context_source": context_source,
                "velocity_trend": metric.velocity_trend,
            }
        )

    state["recommendations"] = recommendations

    critical_count = sum(1 for metric in state["sku_metrics"] if metric.status == "critical")
    watch_count = sum(1 for metric in state["sku_metrics"] if metric.status == "watch")
    healthy_count = sum(1 for metric in state["sku_metrics"] if metric.status == "healthy")
    overstock_count = sum(1 for metric in state["sku_metrics"] if metric.status == "overstock")

    summary_payload = {
        "total_skus_analyzed": len(state["sku_metrics"]),
        "critical_count": critical_count,
        "watch_count": watch_count,
        "healthy_count": healthy_count,
        "overstock_count": overstock_count,
        "skus_skipped": max(0, len(state["raw_records"]) - len(state["sku_metrics"])),
        "overall_health": _overall_health(
            {
                "total_skus_analyzed": len(state["sku_metrics"]),
                "critical_count": critical_count,
                "watch_count": watch_count,
                "healthy_count": healthy_count,
                "overstock_count": overstock_count,
            }
        ),
        "top_priority_skus": [
            metric.sku_id
            for metric in sorted(state["sku_metrics"], key=lambda item: item.reorder_urgency_days)
            if metric.status in {"critical", "watch"}
        ][:5],
    }

    state["final_output"] = {
        "run_id": state["run_id"],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": summary_payload,
        "recommendations": recommendation_dicts,
        "metadata": {
            "llm_model": state["config"].get("ollama", {}).get("model", "llama3.2:1b"),
            "graph_source": state["graph_source"],
            "config_version": "1.0.0",
            "execution_time_ms": 0,
            "partial_data": state["partial_data"],
            "errors": state["errors"],
            "warnings": state["warnings"],
        },
        "disclaimer": DISCLAIMER,
    }

    return state
