"""LangGraph node to validate final output schema compliance."""

from __future__ import annotations

from jsonschema import ValidationError, validate

from agent.logging_utils import add_flow_event
from agent.state import AgentState

OUTPUT_SCHEMA = {
    "type": "object",
    "required": ["run_id", "generated_at", "summary", "recommendations", "metadata", "disclaimer"],
    "properties": {
        "run_id": {"type": "string"},
        "generated_at": {"type": "string"},
        "summary": {
            "type": "object",
            "required": [
                "total_skus_analyzed",
                "critical_count",
                "watch_count",
                "healthy_count",
                "overstock_count",
                "skus_skipped",
                "overall_health",
                "top_priority_skus",
            ],
        },
        "recommendations": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "sku_id",
                    "name",
                    "status",
                    "status_emoji",
                    "days_of_stock",
                    "reorder_qty",
                    "reorder_urgency_days",
                    "recommended_action",
                    "plain_english_explanation",
                    "risk_tags",
                    "confidence",
                    "context_source",
                ],
            },
        },
        "metadata": {"type": "object"},
        "disclaimer": {
            "type": "string",
            "const": "⚠️ ADVISORY ONLY: This analysis is generated by an AI decision-support tool using synthetic mock data. All recommendations require human review and validation before any action is taken. This tool does not place orders, modify systems, or reflect real commercial inventory. Always consult your supply chain team before acting on these suggestions.",
        },
    },
}


def validate_output_node(state: AgentState) -> AgentState:
    """Validate final JSON output against Phase 1 schema expectations."""
    add_flow_event(state, node="validate_output", event="start")
    state["current_node"] = "validate_output"

    payload = state.get("final_output")
    if payload is None:
        state["errors"].append(
            {"node": "validate_output", "sku_id": "", "message": "Missing final_output payload."}
        )
        state["output_valid"] = False
        add_flow_event(state, node="validate_output", event="end", detail="missing_final_output")
        return state

    try:
        validate(instance=payload, schema=OUTPUT_SCHEMA)
        recs = payload.get("recommendations", []) if isinstance(payload, dict) else []
        missing = [
            rec.get("sku_id", "unknown")
            for rec in recs
            if not str(rec.get("plain_english_explanation", "")).strip()
        ]
        if missing:
            raise ValidationError(
                f"plain_english_explanation missing for {len(missing)} SKU(s): {', '.join(missing)}"
            )
        state["output_valid"] = True
    except ValidationError as exc:
        state["errors"].append(
            {"node": "validate_output", "sku_id": "", "message": f"Schema validation failed: {exc.message}"}
        )
        state["output_valid"] = False

    add_flow_event(
        state,
        node="validate_output",
        event="end",
        extra={"output_valid": state["output_valid"], "error_count": len(state["errors"])},
    )

    return state
